version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Sa123456!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - app-network

  app:
    build:
      context: .
    ports:
      - "5000:80"
    depends_on:
      - db
    restart: "on-failure"
    environment:
      ConnectionStrings__MyDatabase: "Server=dbN;User=sa;Password=Sa123456!;"
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
      Database_OnDocker: "true"
    networks:
      - app-network
    # command: bash -c "dotnet ef database update && dotnet run"
volumes:
  db-data:

networks:
  app-network:
    driver: bridge
